### ISSUE TITLE
hdriver crashes when meerstetter not connected

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hcam-drivers#120]
Probably correct, but error message could be clearer

```python
10:50:30 CMM WARNING Unable to get setpoint for CCD1
Traceback (most recent call last):
  File "/usr/bin/hdriver", line 327, in <module>
    gui = GUI()
  File "/usr/bin/hdriver", line 92, in __init__
    self.globals.tecs = meerstetter.CCDTempFrame(topLhsFrame)
  File "/usr/lib/python2.7/site-packages/hcam_drivers/hardware/meerstetter.py", line 277, in __init__
    self.refresh_setpoints()
  File "/usr/lib/python2.7/site-packages/hcam_drivers/hardware/meerstetter.py", line 319, in refresh_setpoints
    widget.configure(text=str(setpoint))
UnboundLocalError: local variable 'setpoint' referenced before assignment
```

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/pull/153
