### ISSUE TITLE
Slide control can be intermittently bad

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hcam-drivers#149]
See Message from Steven Parsons:

```
Having issues trying to move the slide. Tried to block earlier for biases and it gave an error message saying it didn't know where it was, so I homed it. I am fairly sure that it is now homed, but whenever I ask for the position or try to move it it gives the same error message:

ngclin7 insuser:~ 1002 > slide home     
  0%|                                | ?

Slide returned to home position (click "position" to confirm)
ngclin7 insuser:~ 1003 > slide position 
Traceback (most recent call last):
  File "/usr/bin/slide", line 158, in <module>
    command()
  File "/usr/bin/slide", line 90, in command
    print('\n\n'+get_hardware_value(cpars, 'slide', 'position'))
  File "/usr/lib/python2.7/site-packages/hcam_widgets/misc.py", line 691, in get_hardware_value
    raise RuntimeError(err_msg)
RuntimeError: command execution failed: position of slide is undefined until slide homed
 Remote error on Server
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hcam_widgets/misc.py", line 685, in get_hardware_value
    val = proxy.get_value(device, prop)
  File "/usr/lib64/python2.7/site-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/lib64/python2.7/site-packages/Pyro4/core.py", line 476, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
RuntimeError: command execution failed: position of slide is undefined until slide homed
 +--- This exception occured remotely (Pyro) - Remote traceback:
 | Traceback (most recent call last):
 |   File "/usr/lib64/python2.7/site-packages/Pyro4/core.py", line 1421, in handleRequest
 |     data = method(*vargs, **kwargs)  # this is the actual method call to the Pyro object
 |   File "/usr/bin/hwserver", line 173, in get_value
 |     raise RuntimeError('command execution failed: ' + str(err))
 | RuntimeError: command execution failed: position of slide is undefined until slide homed
 +--- End of remote traceback
```

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/pull/153
