### ISSUE TITLE
New meerstetter control widget prevents running hdriver when meerstetters not connected 

### ISSUE THREAD

**Issue by StuartLittlefair** [HiPERCAM/hcam-drivers#97]
```
Traceback (most recent call last):
  File "/Users/sl/anaconda3/bin/hdriver", line 308, in <module>
    gui = GUI()
  File "/Users/sl/anaconda3/bin/hdriver", line 89, in __init__
    self.globals.tecs = meerstetter.CCDTempFrame(topLhsFrame)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hcam_drivers/hardware/meerstetter.py", line 254, in __init__
    ival = ms.get_setpoint(address).value
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hcam_drivers/hardware/meerstetter.py", line 201, in get_setpoint
    return self.get_param(address, param_no, 1)*u.Celsius
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hcam_drivers/hardware/meerstetter.py", line 165, in get_param
    encoded_param_val = self._send_frame(frame_msg)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hcam_drivers/hardware/meerstetter.py", line 132, in _send_frame
    with socketcontext(self.address, self.port) as s:
  File "/Users/sl/anaconda3/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/sl/anaconda3/lib/python3.6/site-packages/hcam_drivers/hardware/meerstetter.py", line 87, in socketcontext
    s.connect((addr, port))
socket.timeout: timed out
```

**Comment by StuartLittlefair** [comment]
fixed in https://github.com/HiPERCAM/hcam-drivers/commit/2e52b0cd5591c0c89aaa93c5ad29fd9ad0d2ff78
